

services:
  backend:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://mysql:123456@db:3306/chat_app
      - JWT_SECRET=secret_key
      - GOOGLE_CLIENT_ID=google_client_id
      - GOOGLE_CLIENT_SECRET=google_client_secret
    networks:
      - chat-backend-network
    volumes:
      - .:/app  
      - /app/node_modules 
    working_dir: /app 
    command: ["npm", "run", "dev"]  

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: chat_app
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: rootpassword123  
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - chat-backend-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - chat-backend-network

networks:
  chat-backend-network:
    driver: bridge

volumes:
  db_data:
